
service: bigdatamodels

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1

functions:
  processbigdatamodel:
    handler: handler.processBigdataModel
    events:
        - s3:
            bucket: pv-bigdatamodels
            event: s3:ObjectCreated:*
            rules:
              - prefix: rawData/
